//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhanEAzam.Admin {
    public partial class Orders {
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.DropDownList ddlSortDir;
        protected global::System.Web.UI.WebControls.TextBox txtKeyword;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.DropDownList ddlPayment;
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.Button btnApply;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Label lblActiveFilters;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvOrders;
        protected global::System.Web.UI.WebControls.Label lblRange;
        protected global::System.Web.UI.WebControls.Button btnFirst;
        protected global::System.Web.UI.WebControls.Button btnPrev;
        protected global::System.Web.UI.WebControls.Label lblPageInfo;
        protected global::System.Web.UI.WebControls.Button btnNext;
        protected global::System.Web.UI.WebControls.Button btnLast;
        protected global::System.Web.UI.WebControls.DropDownList ddlPageSize;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Label lblDetailId;
        protected global::System.Web.UI.WebControls.Button btnBackToList;
        protected global::System.Web.UI.WebControls.Label lblDetailName;
        protected global::System.Web.UI.WebControls.Label lblDetailPhone;
        protected global::System.Web.UI.WebControls.Label lblDetailType;
        protected global::System.Web.UI.WebControls.Label lblDetailAddress;
        protected global::System.Web.UI.WebControls.Label lblDetailPayment;
        protected global::System.Web.UI.WebControls.Label lblDetailDate;
        protected global::System.Web.UI.WebControls.Label lblDetailNotes;
        protected global::System.Web.UI.WebControls.Label lblDetailStatus;
        protected global::System.Web.UI.WebControls.HiddenField hfDetailOrderId;
        protected global::System.Web.UI.WebControls.Panel pnlCancelledBanner;
        protected global::System.Web.UI.WebControls.Label lblCancelledDetail;
        protected global::System.Web.UI.WebControls.Panel pnlStatusControls;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdateStatus;
        protected global::System.Web.UI.WebControls.Label lblStatusMsg;
        protected global::System.Web.UI.WebControls.Label lblStatusError;
        protected global::System.Web.UI.WebControls.Panel pnlCancel;
        protected global::System.Web.UI.WebControls.Literal litCancelHeading;
        protected global::System.Web.UI.WebControls.Panel pnlCancelForm;
        protected global::System.Web.UI.WebControls.Label lblCancelWarning;
        protected global::System.Web.UI.WebControls.TextBox txtCancelReason;
        protected global::System.Web.UI.WebControls.Button btnCancelOrder;
        protected global::System.Web.UI.WebControls.Panel pnlReopen;
        protected global::System.Web.UI.WebControls.TextBox txtReopenReason;
        protected global::System.Web.UI.WebControls.DropDownList ddlReopenStatus;
        protected global::System.Web.UI.WebControls.Button btnReopenOrder;
        protected global::System.Web.UI.WebControls.GridView gvHistory;
        protected global::System.Web.UI.WebControls.GridView gvItems;
        protected global::System.Web.UI.WebControls.Label lblDetailTotal;
    }
}
