//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhanEAzam.Admin {
    public partial class Orders {
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvOrders;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Label lblDetailId;
        protected global::System.Web.UI.WebControls.Button btnBackToList;
        protected global::System.Web.UI.WebControls.Label lblDetailName;
        protected global::System.Web.UI.WebControls.Label lblDetailPhone;
        protected global::System.Web.UI.WebControls.Label lblDetailAddress;
        protected global::System.Web.UI.WebControls.Label lblDetailPayment;
        protected global::System.Web.UI.WebControls.Label lblDetailDate;
        protected global::System.Web.UI.WebControls.Label lblDetailNotes;
        protected global::System.Web.UI.WebControls.Label lblDetailStatus;
        protected global::System.Web.UI.WebControls.HiddenField hfDetailOrderId;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdateStatus;
        protected global::System.Web.UI.WebControls.Label lblStatusMsg;
        protected global::System.Web.UI.WebControls.GridView gvItems;
        protected global::System.Web.UI.WebControls.Label lblDetailTotal;
    }
}
