//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khan_e_azam_website.Pages {
    public partial class OrderTracking {
        protected global::System.Web.UI.WebControls.Panel pnlSearch;
        protected global::System.Web.UI.WebControls.TextBox txtSearchId;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Label lblNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlOrder;
        protected global::System.Web.UI.WebControls.Label lblOrderId;
        protected global::System.Web.UI.WebControls.Label lblStatusBadge;
        protected global::System.Web.UI.WebControls.HiddenField hfStatus;
        protected global::System.Web.UI.WebControls.Label lblCustomerName;
        protected global::System.Web.UI.WebControls.Label lblPhone;
        protected global::System.Web.UI.WebControls.Label lblAddress;
        protected global::System.Web.UI.WebControls.Label lblPayment;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Panel pnlNotes;
        protected global::System.Web.UI.WebControls.Label lblNotes;
        protected global::System.Web.UI.WebControls.Label lblTotal;
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        protected global::System.Web.UI.WebControls.Button btnBackToSearch;
    }
}
